### ISSUE TITLE
I suck at Three.js

### ISSUE THREAD

**Issue by brianpeiris** [brianpeiris/RiftSketch#39]
As a [comment on reddit mentioned](http://www.reddit.com/r/programming/comments/2icmgk/live_coding_in_vr_with_the_oculus_rift_firefox/cl1mfi4), I'm only scratching the surface of what's possible with Three.js and I'm not very artistic. I either need to develop the skills or get someone else to help me create demos.

**Comment by brianpeiris** [comment]
I'm slightly better at Three.js now.

**Comment by InfoHome** [comment]
Take a look to http://openjscad.org/ it's amazing
