### ISSUE TITLE
Will not load

### ISSUE THREAD

**Issue by c-connors** [brianpeiris/RiftSketch#44]
I've checked out the most recent commit (459028ecb926add7a2f91911ccdfe2c821fea684) and it goes to the Unsupported Browser popup on Nightly with the VR plugin.

Looking through the code there's still some angular references ($scope.watch in index.js and ng-controller in index.html). I figured it might just be some files didn't get committed or you're in the middle of development and left it like that for convenience.

**Comment by brianpeiris** [comment]
Yeah, I was in the middle of development in the master branch. The gh-pages branch should still work.

**Comment by brianpeiris** [comment]
I'll try to push the rest of my changes tonight.
