### ISSUE TITLE
Fullscreen Mode to support Oculus 0.7 SDK on Win10

### ISSUE THREAD

**Issue by andreaskoepf** [brianpeiris/RiftSketch#51]
I saw on your todo list is already the point 'fullscreen'. I just wanted to point out that full-screen is very important for Windows 10 Firefox users. Currently when you navigate to http://brianpeiris.github.io/RiftSketch with Nightly and DK2 on Win10 only the position tracking is active and the graphics output still is rendered to the browser window. I believe to fix this a call to 'setFullScreen(true)' in VREffect.js would be required. At least all the other demos on the http://mozvr.com/ page work perfectly on my machine and switching to fullscreen mode seems to be the only difference. (Unfortunately the classic F11 fullscreen-mode is not enough.)

The relevant call is probably:

```javascript
canvas.mozRequestFullScreen( { vrDisplay: vrHMD } );
```

**Comment by brianpeiris** [comment]
Thanks for the feedback. The latest code in the master branch fixes compatibility, which also includes fullscreen support via webvr-boilerplate. If you test it out, I'd love to know if it works in Windows 10. Still working on releasing it though.

**Comment by andreaskoepf** [comment]
Yes, the master branch version allows me to successfully switch into VR mode on my Win10 machine! The only problem: As reported in #47 the editor is displayed rotated 90° to the right. Is there a way to move my position and orientation in the VR world?

**Comment by brianpeiris** [comment]
Cool. No way to rotate your body right now. As a workaround, you can turn your head to look in the _opposite_ direction and then reset the HMD orientation with Ctrl/Alt+Shift+z
