### ISSUE TITLE
C#/C++ support

### ISSUE THREAD

**Issue by dreadbcool4ever** [brianpeiris/RiftSketch#53]
Hey.

Will there be C#/C++ support for coding in the future?

**Comment by leniel** [comment]
+1

**Comment by brianpeiris** [comment]
Sorry, I don't have plans to add support for C#/C++. RiftSketch was built to run on the Web with JavaScript. I might experiment with other languages like TypeScript or ClojureScript, that transpile to JavaScript but C# and C++ will probably always require a native compiler. 
There may be other VR-coding projects out there that target C#/C++. The closest I've found is this demo: https://www.youtube.com/watch?v=t7pyMXM1Fz8
