### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by elswork** [brianpeiris/RiftSketch#79]
I've got this error on 'npi run start':

![image](https://user-images.githubusercontent.com/1455507/153776633-41e7802d-ce03-42f7-8edb-2a3a6151dab2.png)

**Comment by brianpeiris** [comment]
Thanks for the report. I'll look into fixing it.

**Comment by brianpeiris** [comment]
Fixed in #81
